server:
  port: 8002
spring:
    datasource:
      username: idea
      password: zsbscs
      url: jdbc:mysql://8.134.222.113:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-test-query: select 1
        connection-timeout: 20000
        idle-timeout: 300000
        maximum-pool-size: 5
        minimum-idle: 5